#!/bin/sh

TARGET_PATH="$1"

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NOCOL=$(tput sgr0)

echo "PATH: $TARGET_PATH"
for f in "$TARGET_PATH"/*; do
    [ -e "$f" ] || continue
    # ignore files
    if [ -d "$f" ]; then
        REPO_NAME=$(basename "$f")
        # check if a folder does not exist
        if [ -d "$f/.git" ]; then
            STATUS_COMMIT=$(git -C "$f" status -s)
            if [ -n "$STATUS_COMMIT" ]; then
                echo "${RED}[UNCOMMITTED] $REPO_NAME${NOCOL}"
            else
                echo "${GREEN}[NO CHANGES ]${NOCOL} $REPO_NAME"
            fi
            STATUS_PUSH=$(git -C "$f" cherry -v)
			if [ -n "$STATUS_PUSH" ]; then
                echo "${RED}[NOT PUSHED ] $REPO_NAME${NOCOL}"
            fi
        else
            echo "[NOT A REPO ] $REPO_NAME"
        fi
    fi

done
echo ""
